name: Trigger Claude on Label
on:
  pull_request:
    types: [labeled]

jobs:
  mention-claude:
    # This only runs when the "Code Review" label is added
    if: github.event.label.name == 'Code Review'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Post @claude comment
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "@claude please review this PR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
